spring:
  datasource:
    url: jdbc:mysql://192.168.42.128:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  elasticsearch:
    rest:
      uris: http://192.168.42.128:9200
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: localhost