spring:
  datasource:
    url: jdbc:mysql://192.168.42.128:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    mongodb:
      host: 192.168.42.128
      port: 27017
      database: mall-port
  redis:
    host: 192.168.42.128 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
  rabbitmq:
    host: 192.168.42.128
    port: 5672
    virtual-host: /mall
    username: root
    password: 123456
# 日志配置
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: localhost